version: '3'

services:
  php:
    image: yosmy/php
    container_name: yosmy_faker_php
    volumes:
    - ../:/var/www/
    networks:
      - backend
    working_dir: /var/www

networks:
  backend:
    external: true
